@PolicyComplianceCheckerApi_HostAddress = http://localhost:5055

GET {{PolicyComplianceCheckerApi_HostAddress}}/admin/
Accept: application/json

GET {{PolicyComplianceCheckerApi_HostAddress}}/policychecker/
Accept: application/json
###
